import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * FAR Reference Book Sidebar Configuration
 * Auto-generates sidebars for all FAR Parts 1-25
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'doc', id: 'intro'},
    {
      type: 'category',
      label: 'Part 1 - FAR System',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-1'}],
    },
    {
      type: 'category',
      label: 'Part 2 - Definitions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-2'}],
    },
    {
      type: 'category',
      label: 'Part 3 - Improper Business Practices',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-3'}],
    },
    {
      type: 'category',
      label: 'Part 4 - Administrative and Information Matters',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-4'}],
    },
    {
      type: 'category',
      label: 'Part 5 - Publicizing Contract Actions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-5'}],
    },
    {
      type: 'category',
      label: 'Part 6 - Competition Requirements',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-6'}],
    },
    {
      type: 'category',
      label: 'Part 7 - Acquisition Planning',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-7'}],
    },
    {
      type: 'category',
      label: 'Part 8 - Required Sources of Supplies and Services',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-8'}],
    },
    {
      type: 'category',
      label: 'Part 9 - Contractor Qualifications',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-9'}],
    },
    {
      type: 'category',
      label: 'Part 11 - Describing Agency Needs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-11'}],
    },
    {
      type: 'category',
      label: 'Part 12 - Acquisition of Commercial Items',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-12'}],
    },
    {
      type: 'category',
      label: 'Part 13 - Simplified Acquisition Procedures',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-13'}],
    },
    {
      type: 'category',
      label: 'Part 14 - Sealed Bidding',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-14'}],
    },
    {
      type: 'category',
      label: 'Part 15 - Contracting by Negotiation',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-15'}],
    },
    {
      type: 'category',
      label: 'Part 16 - Types of Contracts',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-16'}],
    },
    {
      type: 'category',
      label: 'Part 17 - Special Contracting Methods',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-17'}],
    },
    {
      type: 'category',
      label: 'Part 18 - Emergency Acquisitions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-18'}],
    },
    {
      type: 'category',
      label: 'Part 19 - Small Business Programs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-19'}],
    },
    {
      type: 'category',
      label: 'Part 22 - Application of Labor Laws',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-22'}],
    },
    {
      type: 'category',
      label: 'Part 23 - Environment, Energy, Water, and Sustainability',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-23'}],
    },
    {
      type: 'category',
      label: 'Part 24 - Protection of Privacy and Freedom of Information',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-24'}],
    },
    {
      type: 'category',
      label: 'Part 25 - Foreign Acquisition',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-25'}],
    },
    {
      type: 'category',
      label: 'Part 26 - Other Socioeconomic Programs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-26'}],
    },
    {
      type: 'category',
      label: 'Part 27 - Patents, Data, and Copyrights',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-27'}],
    },
    {
      type: 'category',
      label: 'Part 28 - Bonds and Insurance',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-28'}],
    },
    {
      type: 'category',
      label: 'Part 29 - Taxes',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-29'}],
    },
    {
      type: 'category',
      label: 'Part 30 - Cost Accounting Standards Administration',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-30'}],
    },
    {
      type: 'category',
      label: 'Part 31 - Contract Cost Principles and Procedures',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-31'}],
    },
    {
      type: 'category',
      label: 'Part 32 - Contract Financing',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-32'}],
    },
    {
      type: 'category',
      label: 'Part 33 - Protests, Disputes, and Appeals',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-33'}],
    },
    {
      type: 'category',
      label: 'Part 34 - Major System Acquisition',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-34'}],
    },
    {
      type: 'category',
      label: 'Part 36 - Construction and Architect-Engineer Contracts',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-36'}],
    },
    {
      type: 'category',
      label: 'Part 37 - Service Contracting',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-37'}],
    },
    {
      type: 'category',
      label: 'Part 38 - Federal Supply Schedule Contracting',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-38'}],
    },
    {
      type: 'category',
      label: 'Part 39 - Acquisition of Information Technology',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-39'}],
    },
    {
      type: 'category',
      label: 'Part 40 - Unmanned Aircraft Systems',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-40'}],
    },
    {
      type: 'category',
      label: 'Part 41 - Acquisition of Utility Services',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-41'}],
    },
    {
      type: 'category',
      label: 'Part 42 - Contract Administration and Audit Services',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-42'}],
    },
    {
      type: 'category',
      label: 'Part 43 - Contract Modifications',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-43'}],
    },
    {
      type: 'category',
      label: 'Part 44 - Subcontracting Policies and Procedures',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-44'}],
    },
    {
      type: 'category',
      label: 'Part 45 - Government Property',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-45'}],
    },
  ],
};

export default sidebars;
