import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * FAR Reference Book Sidebar Configuration
 * Organizes FAR Parts 1-3 with chapter titles and categories
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part 1 - FAR System',
      link: {
        type: 'generated-index',
        title: 'Part 1 - Federal Acquisition Regulations System',
        description: 'Establishes the Federal Acquisition Regulations System, including purpose, authority, applicability, and definitions.',
        slug: '/part-1',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Subpart 1.1 - Purpose, Authority, Issuance',
          items: [
            {type: 'autogenerated', dirName: 'part-1'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 2 - Definitions',
      link: {
        type: 'generated-index',
        title: 'Part 2 - Definitions of Words and Terms',
        description: 'Provides definitions for words and terms used throughout the FAR.',
        slug: '/part-2',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'part-2'},
      ],
    },
    {
      type: 'category',
      label: 'Part 3 - Improper Business Practices',
      link: {
        type: 'generated-index',
        title: 'Part 3 - Improper Business Practices and Personal Conflicts of Interest',
        description: 'Addresses policy and procedures for maintaining the integrity and impartiality of the acquisition process.',
        slug: '/part-3',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'part-3'},
      ],
    },
  ],
};

export default sidebars;
