import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * FAR Reference Book Sidebar Configuration
 * Auto-generates sidebars for all FAR Parts 1-25
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'doc', id: 'intro'},
    {
      type: 'category',
      label: 'Part 1 - FAR System',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-1'}],
    },
    {
      type: 'category',
      label: 'Part 2 - Definitions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-2'}],
    },
    {
      type: 'category',
      label: 'Part 3 - Improper Business Practices',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-3'}],
    },
    {
      type: 'category',
      label: 'Part 4 - Administrative and Information Matters',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-4'}],
    },
    {
      type: 'category',
      label: 'Part 5 - Publicizing Contract Actions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-5'}],
    },
    {
      type: 'category',
      label: 'Part 6 - Competition Requirements',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-6'}],
    },
    {
      type: 'category',
      label: 'Part 7 - Acquisition Planning',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-7'}],
    },
    {
      type: 'category',
      label: 'Part 8 - Required Sources of Supplies and Services',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-8'}],
    },
    {
      type: 'category',
      label: 'Part 9 - Contractor Qualifications',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-9'}],
    },
    {
      type: 'category',
      label: 'Part 11 - Describing Agency Needs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-11'}],
    },
    {
      type: 'category',
      label: 'Part 12 - Acquisition of Commercial Items',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-12'}],
    },
    {
      type: 'category',
      label: 'Part 13 - Simplified Acquisition Procedures',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-13'}],
    },
    {
      type: 'category',
      label: 'Part 14 - Sealed Bidding',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-14'}],
    },
    {
      type: 'category',
      label: 'Part 15 - Contracting by Negotiation',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-15'}],
    },
    {
      type: 'category',
      label: 'Part 16 - Types of Contracts',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-16'}],
    },
    {
      type: 'category',
      label: 'Part 17 - Special Contracting Methods',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-17'}],
    },
    {
      type: 'category',
      label: 'Part 18 - Emergency Acquisitions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-18'}],
    },
    {
      type: 'category',
      label: 'Part 19 - Small Business Programs',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-19'}],
    },
    {
      type: 'category',
      label: 'Part 22 - Application of Labor Laws',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-22'}],
    },
    {
      type: 'category',
      label: 'Part 23 - Environment, Energy, Water, and Sustainability',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-23'}],
    },
    {
      type: 'category',
      label: 'Part 24 - Protection of Privacy and Freedom of Information',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-24'}],
    },
    {
      type: 'category',
      label: 'Part 25 - Foreign Acquisition',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'part-25'}],
    },
  ],
};

export default sidebars;
